/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ui/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_ui_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_ui_tickets__ticket_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Ticket */
        patch: operations["edit_ticket_ui_tickets__ticket_id__patch"];
        trace?: never;
    };
    "/ui/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Report */
        post: operations["create_report_ui_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/demo/{scenario}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demo Report */
        post: operations["demo_report_ui_demo__scenario__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/tickets/{ticket_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Investigate */
        post: operations["investigate_ui_tickets__ticket_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/tickets/{ticket_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Reply */
        post: operations["review_reply_ui_tickets__ticket_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/actions/{action_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Action */
        post: operations["review_action_ui_actions__action_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/actions/{action_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline Action */
        post: operations["decline_action_ui_actions__action_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Settings */
        get: operations["settings_ui_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Settings */
        patch: operations["edit_settings_ui_settings_patch"];
        trace?: never;
    };
    "/ui/channels/clickup/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Clickup Reports */
        post: operations["sync_clickup_reports_ui_channels_clickup_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/channels/in_app/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Reports */
        post: operations["sync_reports_ui_channels_in_app_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Knowledge */
        get: operations["knowledge_ui_knowledge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Knowledge */
        patch: operations["edit_knowledge_ui_knowledge_patch"];
        trace?: never;
    };
    "/ui/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activity */
        get: operations["activity_ui_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Insights */
        get: operations["insights_ui_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Problems */
        get: operations["problems_ui_problems_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/problems/{problem_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Problem Detail */
        get: operations["problem_detail_ui_problems__problem_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pipeline */
        get: operations["pipeline_ui_pipeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/priority-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Priority */
        post: operations["preview_priority_ui_priority_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/saved-views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add View */
        post: operations["add_view_ui_saved_views_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tickets */
        get: operations["tickets_tickets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Metrics */
        get: operations["dashboard_metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticket_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence */
        get: operations["evidence_tickets__ticket_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticket_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Investigate */
        post: operations["investigate_tickets__ticket_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticket_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_tickets__ticket_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionRow */
        ActionRow: {
            /** Id */
            id: string;
            /** Ticket Id */
            ticket_id: string;
            /** Run Id */
            run_id: string;
            /** Type */
            type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Evidence Refs */
            evidence_refs: string[];
            /** Reason */
            reason: string;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
            /** Approved At */
            approved_at: string | null;
            /** Reviewer */
            reviewer: string | null;
            /**
             * Mode
             * @constant
             */
            mode: "dry_run";
        };
        /** AgentSetting */
        AgentSetting: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Model
             * @default openai/gpt-4.1-mini
             */
            model: string;
            /**
             * Confidence Threshold
             * @default 0.8
             */
            confidence_threshold: number;
            /**
             * Max Steps
             * @default 6
             */
            max_steps: number;
            /**
             * Instructions
             * @default
             */
            instructions: string;
        };
        /** AppSettings */
        AppSettings: {
            /** Agents */
            agents: {
                [key: string]: components["schemas"]["AgentSetting"];
            };
            /** Connectors */
            connectors: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Channels */
            channels: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Thresholds */
            thresholds: {
                [key: string]: number;
            };
            /** Priority */
            priority: {
                [key: string]: number;
            };
            /** People */
            people?: components["schemas"]["Person"][];
            /** Saved Views */
            saved_views?: components["schemas"]["SavedView"][];
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "account" | "feature" | "gameplay_bug" | "app_bug" | "streak" | "purchase" | "dm_safety" | "cheating" | "merch" | "other";
        /** Cohort */
        Cohort: {
            /** Is Paying */
            is_paying?: boolean | null;
            /** Streak Days */
            streak_days?: number | null;
            /** Source Ref */
            source_ref?: string | null;
        };
        /** EventRow */
        EventRow: {
            /** Id */
            id: string;
            /** Ticket Id */
            ticket_id: string | null;
            /** Kind */
            kind: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
        };
        /** Evidence */
        Evidence: {
            /** Id */
            id: string;
            /** Ticket Id */
            ticket_id: string;
            /** Run Id */
            run_id: string;
            /** Tool */
            tool: string;
            /** Fetched At */
            fetched_at?: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /**
             * Available
             * @default true
             */
            available: boolean;
            /** Source */
            source: string;
        };
        /** FactEntry */
        FactEntry: {
            /** Id */
            id: string;
            category: components["schemas"]["Category"];
            /** Topic */
            topic: string;
            /** Status */
            status: string;
            /** Source */
            source: string;
            /** Checked At */
            checked_at: string;
            /** Answers */
            answers?: {
                [key: string]: string;
            };
            /** Values */
            values?: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InsightsResponse */
        InsightsResponse: {
            /** Tickets */
            tickets: components["schemas"]["Ticket"][];
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Daily */
            daily: {
                [key: string]: unknown;
            }[];
            /** Cost By Model */
            cost_by_model: {
                [key: string]: unknown;
            }[];
            /** Escalation Reasons */
            escalation_reasons: {
                [key: string]: unknown;
            }[];
        };
        /** KnowledgeEdit */
        KnowledgeEdit: {
            /** Reviewer */
            reviewer: string;
            /** Facts */
            facts: components["schemas"]["FactEntry"][];
            /** Fingerprint */
            fingerprint: string;
        };
        /** KnowledgeResponse */
        KnowledgeResponse: {
            /** Facts */
            facts: components["schemas"]["FactEntry"][];
            /** Fingerprint */
            fingerprint: string;
        };
        /** NewReport */
        NewReport: {
            /** Reviewer */
            reviewer: string;
            /**
             * Subject
             * @default
             */
            subject: string;
            /** Body */
            body: string;
            /**
             * User Identifier
             * @default
             */
            user_identifier: string;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "hi" | "hinglish";
            category?: components["schemas"]["Category"] | null;
            /**
             * Provenance
             * @default real
             * @enum {string}
             */
            provenance: "real" | "synthetic";
        };
        /** OverviewResponse */
        OverviewResponse: {
            /** Tickets */
            tickets: components["schemas"]["Ticket"][];
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Stats */
            stats: {
                [key: string]: number | null;
            };
            /** People */
            people: components["schemas"]["Person"][];
            /** Saved Views */
            saved_views: components["schemas"]["SavedView"][];
            /** Sources */
            sources: {
                [key: string]: unknown;
            }[];
            safety: components["schemas"]["SafetyState"];
            /** Generated At */
            generated_at: string;
        };
        /** Person */
        Person: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Categories */
            categories?: components["schemas"]["Category"][];
            /** Modules */
            modules?: string[];
            /** Github Handle */
            github_handle?: string | null;
        };
        /** PipelineResponse */
        PipelineResponse: {
            /** Steps */
            steps: components["schemas"]["PipelineStep"][];
            /** Branches */
            branches: components["schemas"]["PipelineStep"][];
            /** Today */
            today: string;
            /**
             * Safe Mode
             * @default true
             * @constant
             */
            safe_mode: true;
        };
        /** PipelineStep */
        PipelineStep: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Count */
            count: number | null;
            /** Description */
            description: string;
            /** Settings Section */
            settings_section: string;
        };
        /** PriorityPreview */
        PriorityPreview: {
            /** Priority */
            priority: {
                [key: string]: number;
            };
        };
        /** ProblemDetailResponse */
        ProblemDetailResponse: {
            problem: components["schemas"]["ProblemResponse"];
            /** Tickets */
            tickets: components["schemas"]["Ticket"][];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Actions */
            actions: components["schemas"]["ActionRow"][];
        };
        /** ProblemResponse */
        ProblemResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            category: components["schemas"]["Category"];
            /** Ticket Ids */
            ticket_ids: string[];
            /** Ticket Count */
            ticket_count: number;
            /** Users Affected */
            users_affected: number | null;
            /** Paying Users */
            paying_users: number;
            /** Power Users */
            power_users: number;
            /** Unknown Users */
            unknown_users: number;
            /** Status */
            status: string;
            /** Owner */
            owner: string | null;
            /** Summary */
            summary: string;
            /** Root Cause Hypothesis */
            root_cause_hypothesis: string | null;
            /** Confidence */
            confidence: number | null;
            /** Shared Reply */
            shared_reply: string | null;
            /** Language */
            language: string | null;
            /** Trend Percent */
            trend_percent?: number | null;
        };
        /** QueuePreview */
        QueuePreview: {
            /** Tickets */
            tickets: components["schemas"]["QueuePreviewRow"][];
        };
        /** QueuePreviewRow */
        QueuePreviewRow: {
            /** Id */
            id: string;
            /** Subject */
            subject: string;
            /** Before */
            before: number;
            /** After */
            after: number;
        };
        /** Registry */
        Registry: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Fields */
            fields: components["schemas"]["RegistryField"][];
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
            /** Last Check */
            last_check?: string | null;
        };
        /** RegistryField */
        RegistryField: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Type */
            type: string;
            /** Options */
            options?: string[] | null;
            /** Minimum */
            minimum?: number | null;
            /** Maximum */
            maximum?: number | null;
            /** Description */
            description?: string | null;
            /**
             * Readonly
             * @default false
             */
            readonly: boolean;
        };
        /** Reviewed */
        Reviewed: {
            /** Reviewer */
            reviewer: string;
        };
        /** SafetyState */
        SafetyState: {
            /**
             * Safe Mode
             * @default true
             * @constant
             */
            safe_mode: true;
            /**
             * External Dispatch
             * @default false
             * @constant
             */
            external_dispatch: false;
            /**
             * Data Access
             * @default read_only
             * @constant
             */
            data_access: "read_only";
            /** Llm Enabled */
            llm_enabled: boolean;
            /**
             * Real Data Model Policy
             * @default Human PII review required before model use
             */
            real_data_model_policy: string;
        };
        /** SavedView */
        SavedView: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Filters */
            filters?: {
                [key: string]: unknown;
            };
        };
        /** SettingsEdit */
        SettingsEdit: {
            /** Reviewer */
            reviewer: string;
            /** Version */
            version: number;
            /** Config */
            config: {
                [key: string]: unknown;
            };
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Version */
            version: number;
            config: components["schemas"]["AppSettings"];
            /** Registries */
            registries: {
                [key: string]: components["schemas"]["Registry"][];
            };
            /** Secret Status */
            secret_status: {
                [key: string]: "set" | "missing";
            };
            safety: components["schemas"]["SafetyState"];
            /** History */
            history: {
                [key: string]: unknown;
            }[];
        };
        /** SyncResponse */
        SyncResponse: {
            /** Channel */
            channel: string;
            /** Inserted */
            inserted: number;
            /** Fetched */
            fetched: number;
            /**
             * Mode
             * @default dry_run
             * @constant
             */
            mode: "dry_run";
            /**
             * External Dispatch
             * @default false
             * @constant
             */
            external_dispatch: false;
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
        };
        /** Ticket */
        Ticket: {
            /** Id */
            id: string;
            /** Channel */
            channel: string;
            /** Channel Ref */
            channel_ref: string;
            /** Created At */
            created_at: string;
            /** Ingested At */
            ingested_at?: string;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            /**
             * User Identifier
             * @default
             */
            user_identifier: string;
            /** Matiks User Id */
            matiks_user_id?: string | null;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "hi" | "hinglish";
            /**
             * Status
             * @default open
             * @enum {string}
             */
            status: "open" | "investigating" | "drafted" | "resolved" | "escalated" | "closed";
            /** @default other */
            category: components["schemas"]["Category"];
            category_override?: components["schemas"]["Category"] | null;
            /** Language Override */
            language_override?: ("en" | "hi" | "hinglish") | null;
            /**
             * Subcategory
             * @default
             */
            subcategory: string;
            cohort?: components["schemas"]["Cohort"];
            /**
             * Priority Score
             * @default 0
             */
            priority_score: number;
            /** Priority Breakdown */
            priority_breakdown?: {
                [key: string]: number;
            };
            /** Cluster Id */
            cluster_id?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Verdict */
            verdict?: string | null;
            /** Root Cause Hypothesis */
            root_cause_hypothesis?: string | null;
            /** Resolution Type */
            resolution_type?: ("auto" | "assisted" | "escalated") | null;
            /** Assigned To */
            assigned_to?: string | null;
            /**
             * Reply Draft
             * @default
             */
            reply_draft: string;
            /**
             * Internal Summary
             * @default
             */
            internal_summary: string;
            /** Escalation Reason */
            escalation_reason?: string | null;
            /**
             * Injection Flag
             * @default false
             */
            injection_flag: boolean;
            /**
             * Pii Reviewed
             * @default false
             */
            pii_reviewed: boolean;
            /**
             * Provenance
             * @default real
             * @enum {string}
             */
            provenance: "real" | "synthetic";
            /** Evidence Refs */
            evidence_refs?: string[];
            /** Drafted At */
            drafted_at?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            /** Approved At */
            approved_at?: string | null;
            /** Closed At */
            closed_at?: string | null;
            /** Active Run */
            active_run?: string | null;
            /** Handling Seconds */
            handling_seconds?: number | null;
            /** Handling Mode */
            handling_mode?: ("manual" | "assisted") | null;
            /**
             * Revision
             * @default 0
             */
            revision: number;
        };
        /** TicketDetailResponse */
        TicketDetailResponse: {
            ticket: components["schemas"]["Ticket"];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Actions */
            actions: components["schemas"]["ActionRow"][];
            /** Events */
            events: components["schemas"]["EventRow"][];
            /** Tool Calls */
            tool_calls: {
                [key: string]: unknown;
            }[];
            /** Llm Calls */
            llm_calls: {
                [key: string]: unknown;
            }[];
            /** Fact Checks */
            fact_checks: {
                [key: string]: unknown;
            }[];
            /** Guard Note */
            guard_note: string | null;
        };
        /** TicketEdit */
        TicketEdit: {
            /** Reviewer */
            reviewer: string;
            /** Revision */
            revision: number;
            /** Reply Draft */
            reply_draft?: string | null;
            category?: components["schemas"]["Category"] | null;
            /** Assigned To */
            assigned_to?: string | null;
            /** Status */
            status?: ("open" | "escalated" | "closed") | null;
            /** Escalation Reason */
            escalation_reason?: string | null;
            /** Pii Reviewed */
            pii_reviewed?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ViewRequest */
        ViewRequest: {
            /** Reviewer */
            reviewer: string;
            /** Name */
            name: string;
            /** Filters */
            filters: {
                [key: string]: string;
            };
        };
        /** Approval */
        support__api__Approval: {
            /** Reviewer */
            reviewer: string;
            /** Revision */
            revision: number;
            /** Handling Seconds */
            handling_seconds?: number | null;
        };
        /** Approval */
        support__ui_api__Approval: {
            /** Reviewer */
            reviewer: string;
            /** Revision */
            revision: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    overview_ui_overview_get: {
        parameters: {
            query?: {
                person?: string;
                start?: string | null;
                end?: string | null;
                provenance?: "real" | "synthetic" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_ui_tickets__ticket_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_ticket_ui_tickets__ticket_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_ui_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewReport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_report_ui_demo__scenario__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reviewed"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investigate_ui_tickets__ticket_id__process_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["support__ui_api__Approval"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_reply_ui_tickets__ticket_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["support__ui_api__Approval"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_action_ui_actions__action_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["support__ui_api__Approval"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decline_action_ui_actions__action_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reviewed"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settings_ui_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    edit_settings_ui_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_clickup_reports_ui_channels_clickup_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reviewed"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_reports_ui_channels_in_app_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reviewed"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    knowledge_ui_knowledge_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeResponse"];
                };
            };
        };
    };
    edit_knowledge_ui_knowledge_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activity_ui_activity_get: {
        parameters: {
            query?: {
                person?: string;
                provenance?: "real" | "synthetic" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    insights_ui_insights_get: {
        parameters: {
            query?: {
                person?: string;
                start?: string | null;
                end?: string | null;
                provenance?: "real" | "synthetic" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    problems_ui_problems_get: {
        parameters: {
            query?: {
                person?: string;
                provenance?: "real" | "synthetic" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    problem_detail_ui_problems__problem_id__get: {
        parameters: {
            query?: {
                person?: string;
                provenance?: "real" | "synthetic" | "all";
            };
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pipeline_ui_pipeline_get: {
        parameters: {
            query?: {
                person?: string;
                provenance?: "real" | "synthetic" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_priority_ui_priority_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriorityPreview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_view_ui_saved_views_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    tickets_tickets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    dashboard_metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    evidence_tickets__ticket_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investigate_tickets__ticket_id__process_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_tickets__ticket_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["support__api__Approval"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
