import {test} from "node:test";import assert from "node:assert/strict";import {mkdtemp,rm} from "node:fs/promises";import {tmpdir} from "node:os";import {join} from "node:path";
import {allMerch,clickup} from "../lib/clickup";import {isMerch,normalize,redact,assertLocal,type Ticket} from "../lib/core";import {suggest} from "../lib/reply";import {mimeMessage,sendEmail,emailStatus} from "../lib/email";
process.env.CLICKUP_API_TOKEN="test-token";process.env.CLICKUP_LIST_ID="901611930428";process.env.OPENROUTER_API_KEY="test-key";
const task=(id:string,name="Tshirt reward missing")=>({id,name,description:"I earned a reward",date_created:"1000",status:{status:"open"},list:{id:"901611930428"},custom_fields:[{id:"dc7038b0-24fd-4767-a5eb-f5d5f1d1ea17",value:"reporter@example.com"}]});
const fetchMock=(callback:(url:string,init?:RequestInit)=>Response|Promise<Response>)=>((url:any,init?:RequestInit)=>Promise.resolve(callback(String(url),init))) as typeof fetch;
test("all pages are fetched, deduplicated and non-merch excluded",async()=>{let pages=0;const data=await allMerch(fetchMock(url=>{const page=Number(new URL(url).searchParams.get("page"));pages++;return Response.json({tasks:page===0?Array.from({length:100},(_,i)=>task(String(i))):[task("0"),task("101"),task("feature","Add new puzzle module")],last_page:page===1})}));assert.equal(pages,2);assert.equal(data.tickets.length,101);assert.equal(data.scanned,103)});
test("suggestions excluded; merch and cakes included; creator never recipient",()=>{assert.equal(isMerch(task("a","Suggestion: add tshirt colours")),false);assert.equal(isMerch(task("a","Cake delivery question")),true);assert.equal(isMerch(task("a","Cannot restore streak")),false);assert.equal(normalize({...task("a"),custom_fields:[],creator:{email:"creator@example.com"}}).recipient,null)});
test("PII redacted before provider and invalid model response rejected",async()=>{assert.equal(redact("Yash at user@example.com https://site.test 9876543210",["Yash"]),"[name] at [email] [link] [number]");let payload="";await assert.rejects(suggest({...normalize(task("a")),description:"user@example.com",names:[]},"",fetchMock((_u,init)=>{payload=String(init?.body);return Response.json({choices:[{message:{content:'{"wrong":"invalid"}'}}]})})),/invalid draft/);assert.ok(!payload.includes("user@example.com"))});
test("provider errors never include raw error bodies",async()=>{await assert.rejects(clickup("list/1/task",fetchMock(()=>new Response("secret-leak",{status:403}))),error=>error instanceof Error&&error.message.includes("denied")&&!error.message.includes("secret-leak"))});
test("cross-origin mutations rejected",()=>{assert.throws(()=>assertLocal(new Request("http://127.0.0.1:8510/api/send",{headers:{Origin:"http://evil.test"}})),/same-origin/)});
test("MIME uses verified reporter and preserves exact edited body",()=>{const raw=Buffer.from(mimeMessage("sender@example.com","reporter@example.com","Tshirt\nInjected", "Reviewed reply é"),"base64url").toString();assert.ok(raw.includes("To: reporter@example.com\r\n"));assert.equal(Buffer.from(raw.split("\r\n\r\n")[1].trim(),"base64").toString(),"Reviewed reply é")});
test("manual SMTP email preserves recipient and duplicate key sends once",async()=>{for(const key of ["GOOGLE_OAUTH_CLIENT_ID","GOOGLE_OAUTH_CLIENT_SECRET","IMAP_REFRESH_TOKEN"])process.env[key]="test";process.env.IMAP_USER="sender@example.com";const dir=await mkdtemp(join(tmpdir(),"merch-send-"));let sent=0,verified=0;const fetcher=fetchMock(()=>Response.json({access_token:"private",scope:"https://mail.google.com/"}));const factory=()=>({verify:async()=>{verified++},sendMail:async(message:any)=>{sent++;assert.deepEqual(message.envelope,{from:"sender@example.com",to:["reporter@example.com"]});assert.ok(message.raw.toString().includes("To: reporter@example.com"));return{accepted:["reporter@example.com"],messageId:"sent-id"}}});try{const ticket=normalize(task("a"));const first=await sendEmail(ticket,"This is my edited response.","test-idempotency-token",fetcher,dir,factory);const second=await sendEmail(ticket,"This is my edited response.","test-idempotency-token",fetcher,dir,factory);assert.equal(first.id,"sent-id");assert.equal(second.duplicate,true);assert.equal(sent,1);assert.equal(verified,1)}finally{await rm(dir,{recursive:true,force:true})}});
test("SMTP readiness verifies account without sending",async()=>{let sent=0;const status=await emailStatus(fetchMock(()=>Response.json({access_token:"test",scope:"https://mail.google.com/"})),()=>({verify:async()=>{},sendMail:async()=>{sent++;return{}}}));assert.equal(status.ready,true);assert.equal(sent,0)});
test("SMTP rejected authentication is actionable",async()=>{const status=await emailStatus(fetchMock(()=>Response.json({access_token:"test",scope:"https://mail.google.com/"})),()=>({verify:async()=>{throw{code:"EAUTH"}},sendMail:async()=>({})}));assert.equal(status.ready,false);assert.match(status.reason,/authentication was denied/)});
test("milestone physical reward reports match merch",()=>{assert.equal(isMerch(task("a","50-day reward claim")),true);assert.equal(isMerch(task("a","How many coins do I get as puzzle rewards?")),false)});

 test("Next loopback normalization preserves real Host origin checks", () => {
   const url = "http://localhost:8510/api/reply";
   assertLocal(new Request(url, {headers: {Host: "127.0.0.1:8510", Origin: "http://127.0.0.1:8510"}}));
   assertLocal(new Request(url, {headers: {Host: "localhost:8510", Origin: "http://localhost:8510"}}));
   assertLocal(new Request(url, {headers: {Host: "[::1]:8510", Origin: "http://[::1]:8510"}}));
   for (const headers of [
     {Host: "127.0.0.1:8510", Origin: "http://evil.example"},
     {Host: "127.0.0.1:8510", Origin: "http://localhost:8510"},
     {Host: "127.0.0.1:8510", Origin: "http://127.0.0.1:8511"},
     {Host: "evil.example:8510", Origin: "http://evil.example:8510"},
     {Host: "127.0.0.1:8510", Origin: "null"},
     {Host: "127.0.0.1:8511", Origin: "http://127.0.0.1:8511"},
     {Host: "127.0.0.1:8510", Origin: "http://evil.example", "x-forwarded-host": "evil.example:8510"},
   ]) assert.throws(() => assertLocal(new Request(url, {headers: headers as Record<string, string>})));
 });
